/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Entity.Employe_Numéros;
import static Tools.Tools.Message;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdelatif Hamdi
 */
public class Employe extends javax.swing.JFrame {

    /**
     * Creates new form Employe
     */
    public Employe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextempNo = new controls.JTextBox(20);
        TextempName = new controls.JTextBox(20);
        Textaddress = new controls.JTextBox(20);
        Textsalaire = new controls.JTextBox(20);
        TextDébut = new com.toedter.calendar.JDateChooser();
        TextNaissance = new com.toedter.calendar.JDateChooser();
        btnModifier = new controls.JMyBottom();
        btnAjouter = new controls.JMyBottom();
        btnEffacer = new controls.JMyBottom();
        btnTrouver = new controls.JMyBottom();
        btnTout = new controls.JMyBottom();
        btnSup = new controls.JMyBottom();
        btnBack = new controls.JMyBottom();
        jLabel9 = new javax.swing.JLabel();
        RdoNum = new javax.swing.JRadioButton();
        RdoNom = new javax.swing.JRadioButton();
        RdoAddress = new javax.swing.JRadioButton();
        RdoSalaire = new javax.swing.JRadioButton();
        RdoDébut = new javax.swing.JRadioButton();
        RdoNaissance = new javax.swing.JRadioButton();
        RdoDépartement = new javax.swing.JRadioButton();
        TextRecherche = new controls.JTextBox(30);
        btnRecherche = new controls.JMyBottom();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblEmp = new javax.swing.JTable();
        TextDept = new controls.JMyCombo();
        btnAdddept = new controls.JMyBottom();
        jLabel10 = new javax.swing.JLabel();
        TextempNo1 = new controls.JTextBox(12);
        jMyBottom1 = new controls.JMyBottom();
        btnSup1 = new controls.JMyBottom();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabTest = new javax.swing.JTable();
        RdoPhone = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 32)); // NOI18N
        jLabel1.setText("Forme Employé");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numéro :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nom :");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address :");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Salaire :");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("D.Début :");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("D.Naissance :");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Département :");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TextempNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        TextempName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        Textaddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        Textsalaire.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnTrouver.setText("Trouver");
        btnTrouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrouverActionPerformed(evt);
            }
        });

        btnTout.setText("Tout");
        btnTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToutActionPerformed(evt);
            }
        });

        btnSup.setText("Supprimer");
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        btnBack.setText("Retoure");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Rechercher avec :");

        RdoNum.setBackground(new java.awt.Color(255, 255, 255));
        RdoNum.setSelected(true);
        RdoNum.setText("Numéro");
        RdoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoNumActionPerformed(evt);
            }
        });

        RdoNom.setBackground(new java.awt.Color(255, 255, 255));
        RdoNom.setText("Nom");

        RdoAddress.setBackground(new java.awt.Color(255, 255, 255));
        RdoAddress.setText("Address");

        RdoSalaire.setBackground(new java.awt.Color(255, 255, 255));
        RdoSalaire.setText("Salaire");
        RdoSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoSalaireActionPerformed(evt);
            }
        });

        RdoDébut.setBackground(new java.awt.Color(255, 255, 255));
        RdoDébut.setText("Début");

        RdoNaissance.setBackground(new java.awt.Color(255, 255, 255));
        RdoNaissance.setText("Naissance");

        RdoDépartement.setBackground(new java.awt.Color(255, 255, 255));
        RdoDépartement.setText("Département");

        TextRecherche.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnRecherche.setText("Recherche");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        TblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom", "Address", "Salaire", "Début", "Naissance", "Département"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblEmp);

        btnAdddept.setText("+");
        btnAdddept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdddeptActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Num téléphone :");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TextempNo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jMyBottom1.setText("Ajouter");
        jMyBottom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom1ActionPerformed(evt);
            }
        });

        btnSup1.setText("Supprimer");
        btnSup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSup1ActionPerformed(evt);
            }
        });

        TabTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro de téléphone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabTest);

        RdoPhone.setBackground(new java.awt.Color(255, 255, 255));
        RdoPhone.setText("Num");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextempName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Textaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextempNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Textsalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextDébut, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(TextNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextempNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RdoNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RdoNom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RdoAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RdoSalaire)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RdoDébut)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RdoNaissance)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoDépartement))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RdoPhone)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouter, btnEffacer, btnModifier, btnTout, btnTrouver});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSup1, jMyBottom1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextempNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextempName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Textaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Textsalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(TextDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAdddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(TextDébut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextempNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RdoNum)
                            .addComponent(RdoNom)
                            .addComponent(RdoAddress)
                            .addComponent(RdoSalaire)
                            .addComponent(RdoDébut)
                            .addComponent(RdoNaissance)
                            .addComponent(RdoDépartement)
                            .addComponent(RdoPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        setValues();
    e.update();
        p.setEmpNo(Integer.parseInt(TextempNo.getText()));
        p.deleteAllPhonesByEmp();
    for(int i=0 ; i<TabTest.getRowCount();i++){
    p.setPhone(TabTest.getValueAt(i, 0).toString());
    p.add();
    }

    Clear();
    e.getAllRows(TblEmp);

    }//GEN-LAST:event_btnModifierActionPerformed
    Employe_Numéros p = new Employe_Numéros();
    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
setValues();
    e.add();
    p.setEmpNo(Integer.parseInt(TextempNo.getText()));
    for(int i=0 ; i<TabTest.getRowCount();i++){
    p.setPhone(TabTest.getValueAt(i, 0).toString());
    p.add();
    }
    Clear();
    e.getAllRows(TblEmp);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnTrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrouverActionPerformed
String strempNo = (String) Tools.Tools.InputBox("Entrer le Numéro de d'employe ...");
    int empNo = Integer.parseInt(strempNo);
    e.setEmpNo(empNo);
    e.getOneRow(TblEmp);
    }//GEN-LAST:event_btnTrouverActionPerformed

    private void btnToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToutActionPerformed
        // TODO add your handling code here:
        e.getAllRows(TblEmp);
    }//GEN-LAST:event_btnToutActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
    p.setEmpNo(Integer.parseInt(TextempNo.getText()));
    p.deleteAllPhonesByEmp();
    setValues();
    e.delete();
    Clear();
    e.getAllRows(TblEmp);
    }//GEN-LAST:event_btnSupActionPerformed
    private void Clear(){
    Tools.Tools.ClearTexts(this);
    TextempNo.setText(db.go.getAutoNumber("emp", "empNo"));
    btnAjouter.setEnabled(true);
    btnModifier.setEnabled(false);
    btnSup.setEnabled(false);
            DefaultTableModel model = (DefaultTableModel) TabTest.getModel();
        model.setNumRows(0);
    TextempName.requestFocus();
    
    
    
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
this.dispose();
Tools.Tools.OpenForm(new frmMain());
    }//GEN-LAST:event_btnBackActionPerformed

    private void RdoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoNumActionPerformed

    private void RdoSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoSalaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoSalaireActionPerformed
    Entity.Employe e = new Entity.Employe();
    private void setValues(){
    e.setEmpNo(Integer.parseInt(TextempNo.getText()));
    e.setEmpName(TextempName.getText());
    e.setAddress(Textaddress.getText());
    e.setSalaire(Double.parseDouble(Textsalaire.getText()));
    SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
    e.setBDate(String.valueOf(s.format(TextNaissance.getDate())));
    e.setHDate(String.valueOf(s.format(TextDébut.getDate())));
    e.setDeptNo(Integer.parseInt(d.getValueByName((String) TextDept.getSelectedItem())));
    
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnGrp.add(RdoAddress);
        btnGrp.add(RdoDébut);
        btnGrp.add(RdoNom);
        btnGrp.add(RdoSalaire);
        btnGrp.add(RdoNum);
        btnGrp.add(RdoDépartement);
        btnGrp.add(RdoNaissance);
        btnGrp.add(RdoPhone);
        db.go.fillCombo("dept", "deptName", TextDept);
        e.getAllRows(TblEmp);
        Clear();
        TblEmp.getTableHeader().setReorderingAllowed(false);
        TabTest.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_formWindowOpened
        Entity.Département d = new Entity.Département();
    private void btnAdddeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdddeptActionPerformed
        int deptNo = Integer.parseInt(d.getAutoNumber());
        String deptName = (String) Tools.Tools.InputBox("Entrer le nom de département");
        String location = (String) Tools.Tools.InputBox("Entrer la location de département");
        d.setDeptNo(deptNo);
        d.setDeptName(deptName);
        d.setLocation(location);
        d.add();
        db.go.fillCombo("dept", "deptName", TextDept);
    }//GEN-LAST:event_btnAdddeptActionPerformed

    private void TblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblEmpMouseClicked
        // TODO add your handling code here:
                     try{
         int row = TblEmp.getSelectedRow();
         String empNo = TblEmp.getValueAt(row, 0).toString();
         String empName = TblEmp.getValueAt(row, 1).toString();
         String address = TblEmp.getValueAt(row, 2).toString();
         String salaire = TblEmp.getValueAt(row, 3).toString();
         String hDate = TblEmp.getValueAt(row, 4).toString();
         String bDate = TblEmp.getValueAt(row, 5).toString();
         String deptNo = TblEmp.getValueAt(row, 6).toString();
         TextempNo.setText(empNo);
         TextempName.setText(empName);
         Textaddress.setText(address);
         Textsalaire.setText(salaire);
                      SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
             Date hd = s.parse(hDate);
             Date bd = s.parse(bDate);
         TextDébut.setDate(hd);
         TextNaissance.setDate(bd);
         TextDept.setSelectedItem(d.getNameByValue(deptNo));
         p.setEmpNo(Integer.parseInt(TextempNo.getText()));
         p.getAllRows(TabTest);
         btnAjouter.setEnabled(false);
         btnModifier.setEnabled(true);
         btnSup.setEnabled(true);
         }catch(ParseException ex)
         {}
    }//GEN-LAST:event_TblEmpMouseClicked

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        // TODO add your handling code here:
        String cherche ="select * from emp where ";
    if (RdoNum.isSelected()){ cherche+="empNo ="+TextRecherche.getText();}
    else if (RdoNom.isSelected()){ cherche+="empName ='"+TextRecherche.getText()+"'";}
    else if (RdoAddress.isSelected()) { cherche+="address ='"+TextRecherche.getText()+"'";}
    else if (RdoSalaire.isSelected()){ cherche+="salaire ="+TextRecherche.getText();}
    else if (RdoDébut.isSelected()){ cherche+="hDate ='"+TextRecherche.getText()+"'";}
    else if (RdoNaissance.isSelected()){ cherche+="bDate ='"+TextRecherche.getText()+"'";}
    else if (RdoDépartement.isSelected()){ cherche+="deptNo ="+TextRecherche.getText();}
    else {
        cherche+="empNo like '%"+p.getEmpByPhone(TextRecherche.getText())+"%'";}
    e.getCustomRows(cherche, TblEmp);
    }//GEN-LAST:event_btnRechercheActionPerformed

    private void jMyBottom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TabTest.getModel();
        model.addRow(new Object[]{TextempNo1.getText()});
        TextempNo1.setText(""); TextempNo1.requestFocus();
    }//GEN-LAST:event_jMyBottom1ActionPerformed

    private void btnSup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSup1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TabTest.getModel();
        model.setNumRows(0);
        
    }//GEN-LAST:event_btnSup1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdoAddress;
    private javax.swing.JRadioButton RdoDébut;
    private javax.swing.JRadioButton RdoDépartement;
    private javax.swing.JRadioButton RdoNaissance;
    private javax.swing.JRadioButton RdoNom;
    private javax.swing.JRadioButton RdoNum;
    private javax.swing.JRadioButton RdoPhone;
    private javax.swing.JRadioButton RdoSalaire;
    private javax.swing.JTable TabTest;
    private javax.swing.JTable TblEmp;
    private controls.JMyCombo TextDept;
    private com.toedter.calendar.JDateChooser TextDébut;
    private com.toedter.calendar.JDateChooser TextNaissance;
    private javax.swing.JTextField TextRecherche;
    private javax.swing.JTextField Textaddress;
    private javax.swing.JTextField TextempName;
    private javax.swing.JTextField TextempNo;
    private javax.swing.JTextField TextempNo1;
    private javax.swing.JTextField Textsalaire;
    private controls.JMyBottom btnAdddept;
    private controls.JMyBottom btnAjouter;
    private controls.JMyBottom btnBack;
    private controls.JMyBottom btnEffacer;
    private javax.swing.ButtonGroup btnGrp;
    private controls.JMyBottom btnModifier;
    private controls.JMyBottom btnRecherche;
    private controls.JMyBottom btnSup;
    private controls.JMyBottom btnSup1;
    private controls.JMyBottom btnTout;
    private controls.JMyBottom btnTrouver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private controls.JMyBottom jMyBottom1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
